### ISSUE TITLE
Back-end api is not restfull

### ISSUE THREAD

**Issue by mickem** [skritter/skritter-html5#424]
Seems to me that the back-end API:s are not rest full APIs at all instead they are some sort of http query interface. This goes for both legacy and the new API.

**Comment by mcfarljw** [comment]
We are in a transition period from a Google Datastore to MongoDB and plan on making things more restful in the future. We've migrated the data and are working on making the new API mimic the old api, but with the performance benefits on mongo. I'm going to close this because it's not really a client issue.

**Comment by mickem** [comment]
Is there a place to report backend issues?

**Comment by mickem** [comment]
One question regarding backend and API. It sounds a bit like the API will change "ad-hock"?
Or will new API be backwards compatible?

No point for me to invest time in an open source project if it is not really an open source project i.e. half the development is behind closed doors without any public documentation/road map/plan or even an issue tracker...
I'd happily help out but it would have to be towards some sort of fairly stable API so "whatever I do wont stop working randomly"...

**Comment by mcfarljw** [comment]
We don't have any plans to open-source the backend api code, but we do plan on continuing to support a public api for users wishing to access their data make their own clients, scripts or utilities. 

The original code and data layer that supports the v0 api (https://skritter.com/api/v0/docs) was originally written back in 2007 during the original creators college days. That has supported Skritter almost entirely up until a few months ago when we decided it was time to take the plunge and finally cleanup the data layer. It's a big task that involved moving away from Google Datastore and improving the data structure to make full use of MongoDB. We're doing this in stages: get the raw data into mongo, mimic some of the old GET requests to quickly get some of the initial benefits of having the data in the new database and finally start structuring the data in a more sane way.

That being said it's unlikely we'll maintain full backwards compatibility with v0 in the interest of moving forward. As you've mentioned the way the current api works isn't ideal. The new api will likely end up being more restful, but restful is just one of many api design patterns and ultimately we're looking shape things in a way that best supports the client. While we certainly do appreciate any feedback or help you provide it sounds like this might not be the best time to jump in and contribute to the client based on your concerns.

I also noticed your recently updated Google Play review about our support and would like to apologize again for lack of responsiveness from us. I know it's not an excuse, but you hit us at a bad time. It was the last two weeks of our quarter so we were rushing to meet company goals and were down an employee due to paternity leave. We're already a small company of just 4 employees, so made some sacrifices to try and get things done. In retrospect that was a very poor decision and now we have to suffer the consequences. We feel bad about letting our users down and will strive to improve things. We have some big goals that we want to accomplish over the coming months that will hopefully put Skritter back on the right track.

**Comment by mickem** [comment]
I was not asking for legacy backwards compatibility nor an open source backed I was asking as the "new API" was not restful yet you implied it would become restful. Thus I was curious if the "new API" will be changed or if there will be a NEWER API and in that case if the intermediate (current NEW) API will remain in such a case...

Anyways, seems I create more harm then good and the much I do creates conflict in the dialog which was never my intent...

So I am truly sorry for any inconvenience and thank you for you time!

**Comment by prokopcm** [comment]
Hey, sorry I'm late to the conversation. To clarify a little, there's:

- The old "v1" API (called v0) which all the production mobile apps use, and is currently being phased out in certain areas of the Skritter 2.0 client/Android beta.

- The new v2 API, which is still being written. Within the v2 API, a subset the routes are prefixed by `/gae/` e.g. api.skritter.com/v2/gae/progstats and match the inputs/outputs of the corresponding v0 API routes. These routes, along with their inputs and outputs are not likely to change in the near future.

Later on (probably 6 months to a year from now), we want to create new v2 endpoints un-prefixed by the `gae` route which will replace our usage of the v2 gae routes. These routes likely will not match up with the v0 API's endpoints or their inputs/outputs. As an example of a possible route, like you noticed, the vocab info viewer is a pain point in terms of requests. In the v0 API, tying the requests together into a new endpoint, while it would marginally decrease the load time vs. separate requests, would not solve the underlying the server-side bottlenecks, which are the main impediment in this case. In the new unwritten v2 API (or possibly a new v2 gae route), you're absolutely right, we should have a `vocabinfo` endpoint or something similar to mitigate the number of roundtrips for common use cases because they are more of a limiting factor.

As for being RESTful, I'm not going to defend the v0 API at all and had no hand in making it, but you're right in that it isn't fully compliant. We do not have any further development plans for improvement on the v0 API. 

Concerning the development of the v2 API, if you have any feedback on what exists, I welcome it. We don't plan to deviate too much from what Roy Fielding defined. Adherence to a suitable design pattern is generally a good thing, however it need not be blind devotion if one understands the requirements and use cases well. I can't think of an actual example where we'd deviate off the top of my head, but personally I'm generally a little old school in preferring PUT and PATCH be collapsed into a single PUT endpoint with a parameter passed as to whether it's a full or partial representation because of old browser support and not wanting to write nearly-identical sever code.

Like @mcfarljw hinted at, these few weeks are transitional in terms of the data as we flip the v2 `gae` routes live in production. While we welcome feedback, suggestions, pull requests, etc., I'd advise to wait a couple weeks for the dust to settle down before digging into anything data or network perf-related because it's likely going to change. The client code itself likely won't change significantly because of the data updates though as the v2 gae routes are designed to mimic the old API's I/O.
