### ISSUE TITLE
Signup error should show password length error

### ISSUE THREAD

**Issue by Zyst** [skritter/skritter-html5#428]
When signing up I got an error:

<img width="577" alt="screen shot 2017-05-16 at 4 29 20 pm" src="https://cloud.githubusercontent.com/assets/3832380/26129175/d6cca530-3a54-11e7-8407-cf7e549beaa1.png">

Lame! I opened the network tab and this is the response:

<img width="596" alt="screen shot 2017-05-16 at 4 29 41 pm" src="https://cloud.githubusercontent.com/assets/3832380/26129195/e54e59be-3a54-11e7-8736-b439223eb992.png">

Y'all really should have client side errors for PW length, and/or a server response error render that shows that the password was the problem. "Unknown error" doesn't cut it nowadays.

**Comment by prokopcm** [comment]
Hi, good catch! We do have frontend validation and messages for password length (like if it's empty, doesn't match, etc.) among other things, but we didn't catch this case. There's a lot of validation server-side with messages like this, but since we're switching from server-side to frontend messages sometimes we miss a spot. I'll add it in and it'll make it into the next release. Thanks for pointing it out!

**Comment by prokopcm** [comment]
I just patched this up in ff78903. We'll catch the error before submitting the request and just in case also handle it better in the response.

**Comment by prokopcm** [comment]
And since 20 characters is too small in this day and age (case in point, you), I've also upped the server settings to allow for passwords of up to 256 characters (and updated the frontend checks too).

**Comment by Zyst** [comment]
Wowow @prokopcm that was super fast, great job!
