### ISSUE TITLE
No way to remove empty word lists from Android app

### ISSUE THREAD

**Issue by vadimkantorov** [skritter/skritter-html5#442]
Also removing a word list from the app doesn't make it disappear from the word list screen

**Comment by prokopcm** [comment]
Hi, which version of the Android app are you talking about? If you could link to a screenshot of what you mean, that would help too. Thanks!

**Comment by vadimkantorov** [comment]
My version is 2.1.2.

Unfortunately, I can't provide a screenshot at this time because I managed to remove the lists from the web version.

**Comment by prokopcm** [comment]
Ok, all our development is focused on a new Android version that will be released sometime this year (currently in beta which you can sign up through the Google Play store). The issue should hopefully be resolved for you in that version. 

Deleted lists will still show up in the deleted lists section, the system is designed to keep lists around even if you delete them since the goal of Skritter is to help you learn as many words as possible.

**Comment by vadimkantorov** [comment]
"Deleted" category (like in web-version) which seems reasonable. Signed up for the beta!
